"""End-to-end tests for every combination of options."""

from __future__ import annotations

import json
import re
from typing import TYPE_CHECKING, Any

import bs4
import pytest
from griffe import temporary_pypackage
from inline_snapshot import external, outsource, snapshot

if TYPE_CHECKING:
    from mkdocstrings.handlers.python import PythonHandler


options = {
    # General options.
    "find_stubs_package": (True, False),
    "allow_inspection": (True, False),
    "show_bases": (True, False),
    "show_source": (True, False),
    "preload_modules": ((), ("mod1",), None),
    # Heading options.
    "heading_level": (1, 2, 3, 4, 5, 6),
    "show_root_heading": (True, False),
    "show_root_toc_entry": (True, False),
    "show_root_full_path": (True, False),
    "show_root_members_full_path": (True, False),
    "show_object_full_path": (True, False),
    "show_category_heading": (True, False),
    "show_symbol_type_heading": (True, False),
    "show_symbol_type_toc": (True, False),
    # Members options.
    "inherited_members": ((), ("a", "b"), True, False),
    "members": ((), ("a", "b"), True, False, None),
    "members_order": ("source", "alphabetical"),
    "filters": ((), ("!a",), ("a",), None),
    "group_by_category": (True, False),
    "show_submodules": (True, False),
    "summary": (True, False),  # TODO: Test dict.
    "show_labels": (True, False),
    # Docstrings options.
    "docstring_style": ("numpy", "google", "sphinx", None),
    "docstring_options": ({},),  # TODO: Add more examples.
    "docstring_section_style": ("table", "list", "spacy"),
    "merge_init_into_class": (True, False),
    "show_if_no_docstring": (True, False),
    "show_docstring_attributes": (True, False),
    "show_docstring_functions": (True, False),
    "show_docstring_classes": (True, False),
    "show_docstring_modules": (True, False),
    "show_docstring_description": (True, False),
    "show_docstring_examples": (True, False),
    "show_docstring_other_parameters": (True, False),
    "show_docstring_parameters": (True, False),
    "show_docstring_raises": (True, False),
    "show_docstring_receives": (True, False),
    "show_docstring_returns": (True, False),
    "show_docstring_warns": (True, False),
    "show_docstring_yields": (True, False),
    # Signature options.
    "annotations_path": ("brief", "source"),
    "line_length": (1, 10, 60, 120, 1000),
    "show_signature": (True, False),
    "show_signature_annotations": (True, False),
    "signature_crossrefs": (True, False),
    "separate_signature": (True, False),
    "unwrap_annotated": (True, False),
}

code = """
    def foo(a: int, b: str) -> None:
        '''Docstring for `foo`.'''

    class Bar:
        '''Docstring for `Bar`.'''

        def __init__(self, a: int, b: str) -> None:
            '''Docstring for `Bar.__init__`.'''
            self.c = a + b
            '''Docstring for `Bar.c`.'''

        def foo(self, a: int, b: str) -> None:
            '''Docstring.'''

    baz: int = 42
    '''Docstring for `baz`.'''

    class Qux(Bar):
        '''Docstring for `Qux`.'''
"""


def _normalize_html(html: str) -> str:
    soup = bs4.BeautifulSoup(html, features="html.parser")
    html = soup.prettify()
    html = re.sub(r"\b(0x)[a-f0-9]+\b", r"\1...", html)
    html = re.sub(r"^(Build Date UTC ?:).+", r"\1...", html, flags=re.MULTILINE)
    html = re.sub(r"\b[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}\b", r"...", html)
    html = re.sub(r'(?<=id="cell-id=)\w+(?=")', r"...", html)
    return html  # noqa: RET504


def _render(handler: PythonHandler, final_options: dict[str, Any]) -> str:
    final_options.pop("handler", None)
    final_options.pop("session_handler", None)
    handler_options = final_options.copy()
    with temporary_pypackage("pkg", {"__init__.py": code}) as tmppkg:
        handler._paths.insert(0, tmppkg.tmpdir)
        data = handler.collect("pkg", handler_options)
        html = handler.render(data, handler_options)
        return _normalize_html(html)


def _render_options(options: dict[str, Any]) -> str:
    return f"<!--\n{json.dumps(options, indent=2, sort_keys=True)}\n-->\n\n"


snapshots_signatures = snapshot({(
    ("annotations_path", "brief"),
    ("separate_signature", False),
    ("show_signature", True),
    ("show_signature_annotations", False),
    ("signature_crossrefs", True),
    ("unwrap_annotated", True),
): external("aa8350e05ae2*.html"), (
    ("annotations_path", "source"),
    ("separate_signature", False),
    ("show_signature", True),
    ("show_signature_annotations", True),
    ("signature_crossrefs", True),
    ("unwrap_annotated", False),
): external("9c03e5e13ab0*.html"), (
    ("annotations_path", "brief"),
    ("separate_signature", True),
    ("show_signature", False),
    ("show_signature_annotations", True),
    ("signature_crossrefs", False),
    ("unwrap_annotated", True),
): external("bcb9581db895*.html"), (
    ("annotations_path", "source"),
    ("separate_signature", True),
    ("show_signature", False),
    ("show_signature_annotations", False),
    ("signature_crossrefs", True),
    ("unwrap_annotated", False),
): external("02b683b2892f*.html"), (
    ("annotations_path", "brief"),
    ("separate_signature", False),
    ("show_signature", False),
    ("show_signature_annotations", True),
    ("signature_crossrefs", False),
    ("unwrap_annotated", False),
): external("ff3e24f9ca5f*.html"), (
    ("annotations_path", "source"),
    ("separate_signature", False),
    ("show_signature", True),
    ("show_signature_annotations", False),
    ("signature_crossrefs", True),
    ("unwrap_annotated", False),
): external("e29e862e738d*.html"), (
    ("annotations_path", "source"),
    ("separate_signature", False),
    ("show_signature", True),
    ("show_signature_annotations", True),
    ("signature_crossrefs", False),
    ("unwrap_annotated", False),
): external("e0ef3a5b5202*.html"), (
    ("annotations_path", "brief"),
    ("separate_signature", True),
    ("show_signature", True),
    ("show_signature_annotations", True),
    ("signature_crossrefs", True),
    ("unwrap_annotated", False),
): external("5c1fe7773134*.html"), (
    ("annotations_path", "source"),
    ("separate_signature", False),
    ("show_signature", False),
    ("show_signature_annotations", True),
    ("signature_crossrefs", True),
    ("unwrap_annotated", True),
): external("ef503ea42445*.html"), (
    ("annotations_path", "brief"),
    ("separate_signature", False),
    ("show_signature", True),
    ("show_signature_annotations", False),
    ("signature_crossrefs", True),
    ("unwrap_annotated", False),
): external("8698847071af*.html"), (
    ("annotations_path", "source"),
    ("separate_signature", False),
    ("show_signature", False),
    ("show_signature_annotations", False),
    ("signature_crossrefs", False),
    ("unwrap_annotated", True),
): external("fd182961534f*.html"), (
    ("annotations_path", "brief"),
    ("separate_signature", False),
    ("show_signature", False),
    ("show_signature_annotations", True),
    ("signature_crossrefs", True),
    ("unwrap_annotated", True),
): external("93d1ca9b0106*.html"), (
    ("annotations_path", "brief"),
    ("separate_signature", False),
    ("show_signature", False),
    ("show_signature_annotations", False),
    ("signature_crossrefs", True),
    ("unwrap_annotated", False),
): external("5cd626605cfd*.html"), (
    ("annotations_path", "source"),
    ("separate_signature", True),
    ("show_signature", True),
    ("show_signature_annotations", True),
    ("signature_crossrefs", False),
    ("unwrap_annotated", False),
): external("ead4bad3326f*.html"), (
    ("annotations_path", "brief"),
    ("separate_signature", True),
    ("show_signature", True),
    ("show_signature_annotations", False),
    ("signature_crossrefs", False),
    ("unwrap_annotated", False),
): external("4fadb7743e54*.html"), (
    ("annotations_path", "brief"),
    ("separate_signature", True),
    ("show_signature", False),
    ("show_signature_annotations", False),
    ("signature_crossrefs", False),
    ("unwrap_annotated", True),
): external("38887e43905d*.html"), (
    ("annotations_path", "source"),
    ("separate_signature", False),
    ("show_signature", False),
    ("show_signature_annotations", False),
    ("signature_crossrefs", True),
    ("unwrap_annotated", True),
): external("2be56badfbc8*.html"), (
    ("annotations_path", "brief"),
    ("separate_signature", True),
    ("show_signature", True),
    ("show_signature_annotations", False),
    ("signature_crossrefs", False),
    ("unwrap_annotated", True),
): external("5b1495cc546d*.html"), (
    ("annotations_path", "source"),
    ("separate_signature", True),
    ("show_signature", True),
    ("show_signature_annotations", True),
    ("signature_crossrefs", False),
    ("unwrap_annotated", True),
): external("c890e5ae580f*.html"), (
    ("annotations_path", "source"),
    ("separate_signature", True),
    ("show_signature", False),
    ("show_signature_annotations", True),
    ("signature_crossrefs", True),
    ("unwrap_annotated", False),
): external("4568d8f647aa*.html"), (
    ("annotations_path", "brief"),
    ("separate_signature", True),
    ("show_signature", True),
    ("show_signature_annotations", True),
    ("signature_crossrefs", True),
    ("unwrap_annotated", True),
): external("fbef590cef25*.html"), (
    ("annotations_path", "brief"),
    ("separate_signature", False),
    ("show_signature", False),
    ("show_signature_annotations", True),
    ("signature_crossrefs", False),
    ("unwrap_annotated", True),
): external("8106f051c1ad*.html"), (
    ("annotations_path", "source"),
    ("separate_signature", False),
    ("show_signature", False),
    ("show_signature_annotations", True),
    ("signature_crossrefs", False),
    ("unwrap_annotated", False),
): external("5552b40a36b3*.html"), (
    ("annotations_path", "source"),
    ("separate_signature", False),
    ("show_signature", True),
    ("show_signature_annotations", False),
    ("signature_crossrefs", False),
    ("unwrap_annotated", True),
): external("054bc0f04f7a*.html"), (
    ("annotations_path", "brief"),
    ("separate_signature", False),
    ("show_signature", False),
    ("show_signature_annotations", False),
    ("signature_crossrefs", False),
    ("unwrap_annotated", False),
): external("56ef40df45d8*.html"), (
    ("annotations_path", "source"),
    ("separate_signature", True),
    ("show_signature", False),
    ("show_signature_annotations", False),
    ("signature_crossrefs", True),
    ("unwrap_annotated", True),
): external("745fc7dc33c0*.html"), (
    ("annotations_path", "source"),
    ("separate_signature", True),
    ("show_signature", True),
    ("show_signature_annotations", False),
    ("signature_crossrefs", False),
    ("unwrap_annotated", True),
): external("5b805fa7b428*.html"), (
    ("annotations_path", "source"),
    ("separate_signature", False),
    ("show_signature", True),
    ("show_signature_annotations", False),
    ("signature_crossrefs", True),
    ("unwrap_annotated", True),
): external("473fa37c0dd1*.html"), (
    ("annotations_path", "brief"),
    ("separate_signature", True),
    ("show_signature", False),
    ("show_signature_annotations", True),
    ("signature_crossrefs", True),
    ("unwrap_annotated", False),
): external("4f31cde98503*.html"), (
    ("annotations_path", "brief"),
    ("separate_signature", False),
    ("show_signature", True),
    ("show_signature_annotations", False),
    ("signature_crossrefs", False),
    ("unwrap_annotated", False),
): external("621d7727b971*.html"), (
    ("annotations_path", "brief"),
    ("separate_signature", True),
    ("show_signature", True),
    ("show_signature_annotations", False),
    ("signature_crossrefs", True),
    ("unwrap_annotated", False),
): external("1eebd02ca2ba*.html"), (
    ("annotations_path", "source"),
    ("separate_signature", False),
    ("show_signature", True),
    ("show_signature_annotations", False),
    ("signature_crossrefs", False),
    ("unwrap_annotated", False),
): external("e20d1a9d7d9f*.html"), (
    ("annotations_path", "source"),
    ("separate_signature", True),
    ("show_signature", False),
    ("show_signature_annotations", False),
    ("signature_crossrefs", False),
    ("unwrap_annotated", True),
): external("61a9ad06a827*.html"), (
    ("annotations_path", "brief"),
    ("separate_signature", True),
    ("show_signature", False),
    ("show_signature_annotations", False),
    ("signature_crossrefs", False),
    ("unwrap_annotated", False),
): external("3ee14a7ea493*.html"), (
    ("annotations_path", "brief"),
    ("separate_signature", True),
    ("show_signature", False),
    ("show_signature_annotations", True),
    ("signature_crossrefs", False),
    ("unwrap_annotated", False),
): external("0052f50a8eb6*.html"), (
    ("annotations_path", "source"),
    ("separate_signature", False),
    ("show_signature", False),
    ("show_signature_annotations", False),
    ("signature_crossrefs", True),
    ("unwrap_annotated", False),
): external("c4d8cb8f070e*.html"), (
    ("annotations_path", "source"),
    ("separate_signature", False),
    ("show_signature", False),
    ("show_signature_annotations", True),
    ("signature_crossrefs", True),
    ("unwrap_annotated", False),
): external("7cb040ea303d*.html"), (
    ("annotations_path", "source"),
    ("separate_signature", True),
    ("show_signature", True),
    ("show_signature_annotations", True),
    ("signature_crossrefs", True),
    ("unwrap_annotated", True),
): external("e8e8b7f507e0*.html"), (
    ("annotations_path", "source"),
    ("separate_signature", True),
    ("show_signature", True),
    ("show_signature_annotations", False),
    ("signature_crossrefs", True),
    ("unwrap_annotated", False),
): external("8cbf9adc0357*.html"), (
    ("annotations_path", "brief"),
    ("separate_signature", True),
    ("show_signature", False),
    ("show_signature_annotations", True),
    ("signature_crossrefs", True),
    ("unwrap_annotated", True),
): external("aa4582f77a87*.html"), (
    ("annotations_path", "brief"),
    ("separate_signature", False),
    ("show_signature", True),
    ("show_signature_annotations", True),
    ("signature_crossrefs", False),
    ("unwrap_annotated", True),
): external("8a94076b256b*.html"), (
    ("annotations_path", "brief"),
    ("separate_signature", True),
    ("show_signature", True),
    ("show_signature_annotations", True),
    ("signature_crossrefs", False),
    ("unwrap_annotated", True),
): external("efffc9d74503*.html"), (
    ("annotations_path", "brief"),
    ("separate_signature", False),
    ("show_signature", False),
    ("show_signature_annotations", True),
    ("signature_crossrefs", True),
    ("unwrap_annotated", False),
): external("c41b52887fe1*.html"), (
    ("annotations_path", "source"),
    ("separate_signature", False),
    ("show_signature", False),
    ("show_signature_annotations", True),
    ("signature_crossrefs", False),
    ("unwrap_annotated", True),
): external("7480aa8554de*.html"), (
    ("annotations_path", "source"),
    ("separate_signature", True),
    ("show_signature", True),
    ("show_signature_annotations", True),
    ("signature_crossrefs", True),
    ("unwrap_annotated", False),
): external("6922676ac2ae*.html"), (
    ("annotations_path", "brief"),
    ("separate_signature", True),
    ("show_signature", False),
    ("show_signature_annotations", False),
    ("signature_crossrefs", True),
    ("unwrap_annotated", True),
): external("061dae51b55e*.html"), (
    ("annotations_path", "source"),
    ("separate_signature", False),
    ("show_signature", True),
    ("show_signature_annotations", True),
    ("signature_crossrefs", True),
    ("unwrap_annotated", True),
): external("0b03b1ca220b*.html"), (
    ("annotations_path", "source"),
    ("separate_signature", True),
    ("show_signature", False),
    ("show_signature_annotations", True),
    ("signature_crossrefs", False),
    ("unwrap_annotated", False),
): external("e059dfb9589b*.html"), (
    ("annotations_path", "brief"),
    ("separate_signature", False),
    ("show_signature", True),
    ("show_signature_annotations", True),
    ("signature_crossrefs", False),
    ("unwrap_annotated", False),
): external("17709622996f*.html"), (
    ("annotations_path", "brief"),
    ("separate_signature", False),
    ("show_signature", False),
    ("show_signature_annotations", False),
    ("signature_crossrefs", False),
    ("unwrap_annotated", True),
): external("0e43d41577d5*.html"), (
    ("annotations_path", "brief"),
    ("separate_signature", True),
    ("show_signature", True),
    ("show_signature_annotations", True),
    ("signature_crossrefs", False),
    ("unwrap_annotated", False),
): external("9d142b040f09*.html"), (
    ("annotations_path", "source"),
    ("separate_signature", True),
    ("show_signature", False),
    ("show_signature_annotations", False),
    ("signature_crossrefs", False),
    ("unwrap_annotated", False),
): external("08090b9fe0f4*.html"), (
    ("annotations_path", "brief"),
    ("separate_signature", False),
    ("show_signature", True),
    ("show_signature_annotations", False),
    ("signature_crossrefs", False),
    ("unwrap_annotated", True),
): external("6a18b22159bb*.html"), (
    ("annotations_path", "brief"),
    ("separate_signature", True),
    ("show_signature", True),
    ("show_signature_annotations", False),
    ("signature_crossrefs", True),
    ("unwrap_annotated", True),
): external("5ae2ecad4151*.html"), (
    ("annotations_path", "source"),
    ("separate_signature", True),
    ("show_signature", True),
    ("show_signature_annotations", False),
    ("signature_crossrefs", True),
    ("unwrap_annotated", True),
): external("c953c91e0c1f*.html"), (
    ("annotations_path", "source"),
    ("separate_signature", True),
    ("show_signature", True),
    ("show_signature_annotations", False),
    ("signature_crossrefs", False),
    ("unwrap_annotated", False),
): external("0f27d0a8298d*.html"), (
    ("annotations_path", "source"),
    ("separate_signature", False),
    ("show_signature", True),
    ("show_signature_annotations", True),
    ("signature_crossrefs", False),
    ("unwrap_annotated", True),
): external("04447c668f09*.html"), (
    ("annotations_path", "source"),
    ("separate_signature", False),
    ("show_signature", False),
    ("show_signature_annotations", False),
    ("signature_crossrefs", False),
    ("unwrap_annotated", False),
): external("c5920eb13047*.html"), (
    ("annotations_path", "source"),
    ("separate_signature", True),
    ("show_signature", False),
    ("show_signature_annotations", True),
    ("signature_crossrefs", True),
    ("unwrap_annotated", True),
): external("b601f9412b7b*.html"), (
    ("annotations_path", "brief"),
    ("separate_signature", False),
    ("show_signature", True),
    ("show_signature_annotations", True),
    ("signature_crossrefs", True),
    ("unwrap_annotated", True),
): external("b2ae15ece50b*.html"), (
    ("annotations_path", "source"),
    ("separate_signature", True),
    ("show_signature", False),
    ("show_signature_annotations", True),
    ("signature_crossrefs", False),
    ("unwrap_annotated", True),
): external("94540c6d47a4*.html"), (
    ("annotations_path", "brief"),
    ("separate_signature", False),
    ("show_signature", True),
    ("show_signature_annotations", True),
    ("signature_crossrefs", True),
    ("unwrap_annotated", False),
): external("56214738d8cd*.html"), (
    ("annotations_path", "brief"),
    ("separate_signature", False),
    ("show_signature", False),
    ("show_signature_annotations", False),
    ("signature_crossrefs", True),
    ("unwrap_annotated", True),
): external("04735fd80fac*.html"), (
    ("annotations_path", "brief"),
    ("separate_signature", True),
    ("show_signature", False),
    ("show_signature_annotations", False),
    ("signature_crossrefs", True),
    ("unwrap_annotated", False),
): external("2be52b4289ad*.html")})

snapshots_members = snapshot({(
    ("filters", ("!a",)),
    ("inherited_members", True),
    ("members", None),
    ("members_order", "alphabetical"),
    ("summary", True),
): external("b66e2406e0b6*.html"), (
    ("filters", ()),
    ("inherited_members", ("a", "b")),
    ("members", ()),
    ("members_order", "source"),
    ("summary", True),
): external("ae3b7994a72e*.html"), (
    ("filters", ()),
    ("inherited_members", ()),
    ("members", ()),
    ("members_order", "alphabetical"),
    ("summary", False),
): external("ba560399e445*.html"), (
    ("filters", None),
    ("inherited_members", ("a", "b")),
    ("members", True),
    ("members_order", "source"),
    ("summary", False),
): external("8bc4bcf52f91*.html"), (
    ("filters", ("!a",)),
    ("inherited_members", False),
    ("members", False),
    ("members_order", "alphabetical"),
    ("summary", True),
): external("10ad812d9e3f*.html"), (
    ("filters", ("!a",)),
    ("inherited_members", ()),
    ("members", None),
    ("members_order", "source"),
    ("summary", False),
): external("86b389fd7f13*.html"), (
    ("filters", ("a",)),
    ("inherited_members", False),
    ("members", True),
    ("members_order", "alphabetical"),
    ("summary", True),
): external("45deaea79f50*.html"), (
    ("filters", None),
    ("inherited_members", False),
    ("members", ("a", "b")),
    ("members_order", "source"),
    ("summary", False),
): external("c8966219e87e*.html"), (
    ("filters", None),
    ("inherited_members", ("a", "b")),
    ("members", ()),
    ("members_order", "alphabetical"),
    ("summary", False),
): external("7e9aaff3ff4a*.html"), (
    ("filters", ()),
    ("inherited_members", True),
    ("members", False),
    ("members_order", "source"),
    ("summary", False),
): external("9572a0b4eff9*.html"), (
    ("filters", ("a",)),
    ("inherited_members", False),
    ("members", True),
    ("members_order", "alphabetical"),
    ("summary", False),
): external("06ec6b2827ef*.html"), (
    ("filters", ("a",)),
    ("inherited_members", ("a", "b")),
    ("members", True),
    ("members_order", "alphabetical"),
    ("summary", True),
): external("857540c0804c*.html"), (
    ("filters", ()),
    ("inherited_members", ("a", "b")),
    ("members", ("a", "b")),
    ("members_order", "source"),
    ("summary", True),
): external("2f0677da80bc*.html"), (
    ("filters", ("a",)),
    ("inherited_members", True),
    ("members", ("a", "b")),
    ("members_order", "alphabetical"),
    ("summary", False),
): external("7ee885dc6a17*.html"), (
    ("filters", None),
    ("inherited_members", ("a", "b")),
    ("members", ()),
    ("members_order", "source"),
    ("summary", False),
): external("ed4baedfc1d9*.html"), (
    ("filters", ("!a",)),
    ("inherited_members", ()),
    ("members", None),
    ("members_order", "source"),
    ("summary", True),
): external("1e628c344afb*.html"), (
    ("filters", None),
    ("inherited_members", ("a", "b")),
    ("members", ("a", "b")),
    ("members_order", "source"),
    ("summary", False),
): external("ef5dc2f57c29*.html"), (
    ("filters", ("a",)),
    ("inherited_members", ("a", "b")),
    ("members", False),
    ("members_order", "alphabetical"),
    ("summary", False),
): external("dbec3e1f7c56*.html"), (
    ("filters", ("a",)),
    ("inherited_members", True),
    ("members", None),
    ("members_order", "source"),
    ("summary", True),
): external("002705e2af89*.html"), (
    ("filters", ()),
    ("inherited_members", False),
    ("members", ()),
    ("members_order", "alphabetical"),
    ("summary", True),
): external("83c2ac97e8b3*.html"), (
    ("filters", ()),
    ("inherited_members", True),
    ("members", ("a", "b")),
    ("members_order", "source"),
    ("summary", True),
): external("b60eaf6d5a76*.html"), (
    ("filters", None),
    ("inherited_members", True),
    ("members", ()),
    ("members_order", "source"),
    ("summary", False),
): external("52194fb16cdd*.html"), (
    ("filters", ()),
    ("inherited_members", ("a", "b")),
    ("members", True),
    ("members_order", "alphabetical"),
    ("summary", False),
): external("a70420e951df*.html"), (
    ("filters", None),
    ("inherited_members", False),
    ("members", None),
    ("members_order", "source"),
    ("summary", False),
): external("1bf278547176*.html"), (
    ("filters", ("a",)),
    ("inherited_members", ("a", "b")),
    ("members", False),
    ("members_order", "source"),
    ("summary", False),
): external("268bbae05bf4*.html"), (
    ("filters", ("!a",)),
    ("inherited_members", False),
    ("members", True),
    ("members_order", "source"),
    ("summary", False),
): external("b72b63b1cdf1*.html"), (
    ("filters", None),
    ("inherited_members", ()),
    ("members", False),
    ("members_order", "alphabetical"),
    ("summary", False),
): external("86c5ac40918b*.html"), (
    ("filters", ()),
    ("inherited_members", ("a", "b")),
    ("members", None),
    ("members_order", "source"),
    ("summary", True),
): external("824d365fc3a8*.html"), (
    ("filters", ("!a",)),
    ("inherited_members", ()),
    ("members", True),
    ("members_order", "source"),
    ("summary", False),
): external("0f12d3685f2d*.html"), (
    ("filters", ("a",)),
    ("inherited_members", ("a", "b")),
    ("members", ("a", "b")),
    ("members_order", "alphabetical"),
    ("summary", False),
): external("6db5831def1b*.html"), (
    ("filters", None),
    ("inherited_members", ()),
    ("members", ()),
    ("members_order", "alphabetical"),
    ("summary", False),
): external("25341ab6d50b*.html"), (
    ("filters", ("!a",)),
    ("inherited_members", ()),
    ("members", None),
    ("members_order", "alphabetical"),
    ("summary", True),
): external("25769bdeec20*.html"), (
    ("filters", ("a",)),
    ("inherited_members", True),
    ("members", ()),
    ("members_order", "source"),
    ("summary", True),
): external("01d987e40045*.html"), (
    ("filters", ("!a",)),
    ("inherited_members", ()),
    ("members", True),
    ("members_order", "alphabetical"),
    ("summary", False),
): external("5103282d57a3*.html"), (
    ("filters", ("a",)),
    ("inherited_members", True),
    ("members", False),
    ("members_order", "alphabetical"),
    ("summary", True),
): external("043d4814270e*.html"), (
    ("filters", ("!a",)),
    ("inherited_members", True),
    ("members", None),
    ("members_order", "source"),
    ("summary", True),
): external("4b4fa906fe82*.html"), (
    ("filters", ("a",)),
    ("inherited_members", ()),
    ("members", True),
    ("members_order", "alphabetical"),
    ("summary", True),
): external("28fefa2a7436*.html"), (
    ("filters", ("!a",)),
    ("inherited_members", ("a", "b")),
    ("members", True),
    ("members_order", "alphabetical"),
    ("summary", True),
): external("f26d452ac7fa*.html"), (
    ("filters", ("!a",)),
    ("inherited_members", False),
    ("members", ()),
    ("members_order", "source"),
    ("summary", True),
): external("f2f2fc37a90c*.html"), (
    ("filters", ()),
    ("inherited_members", ()),
    ("members", None),
    ("members_order", "source"),
    ("summary", True),
): external("c63de7c354bf*.html"), (
    ("filters", ("a",)),
    ("inherited_members", False),
    ("members", None),
    ("members_order", "alphabetical"),
    ("summary", True),
): external("2b0727bfe5ee*.html"), (
    ("filters", ("a",)),
    ("inherited_members", ()),
    ("members", None),
    ("members_order", "alphabetical"),
    ("summary", True),
): external("66d4b77303cd*.html"), (
    ("filters", ()),
    ("inherited_members", True),
    ("members", None),
    ("members_order", "source"),
    ("summary", True),
): external("68cf299d4ed7*.html"), (
    ("filters", ()),
    ("inherited_members", ("a", "b")),
    ("members", False),
    ("members_order", "alphabetical"),
    ("summary", True),
): external("129b6eb0bba7*.html"), (
    ("filters", ("a",)),
    ("inherited_members", ("a", "b")),
    ("members", ()),
    ("members_order", "source"),
    ("summary", False),
): external("b561e016dedd*.html"), (
    ("filters", ("!a",)),
    ("inherited_members", True),
    ("members", ()),
    ("members_order", "source"),
    ("summary", False),
): external("89a0613342d8*.html"), (
    ("filters", ()),
    ("inherited_members", True),
    ("members", True),
    ("members_order", "alphabetical"),
    ("summary", False),
): external("5bdf1efcbbac*.html"), (
    ("filters", None),
    ("inherited_members", True),
    ("members", ("a", "b")),
    ("members_order", "alphabetical"),
    ("summary", True),
): external("164aa42de215*.html"), (
    ("filters", ("!a",)),
    ("inherited_members", ("a", "b")),
    ("members", None),
    ("members_order", "alphabetical"),
    ("summary", False),
): external("9f6e423a3e90*.html"), (
    ("filters", ()),
    ("inherited_members", ("a", "b")),
    ("members", True),
    ("members_order", "alphabetical"),
    ("summary", True),
): external("5cc910ba4d5d*.html"), (
    ("filters", ("!a",)),
    ("inherited_members", ()),
    ("members", ("a", "b")),
    ("members_order", "source"),
    ("summary", False),
): external("fbf2bb8d4f68*.html"), (
    ("filters", ("!a",)),
    ("inherited_members", False),
    ("members", None),
    ("members_order", "source"),
    ("summary", True),
): external("3f9302918a4f*.html"), (
    ("filters", ()),
    ("inherited_members", True),
    ("members", True),
    ("members_order", "alphabetical"),
    ("summary", True),
): external("f54bb4294eff*.html"), (
    ("filters", ("!a",)),
    ("inherited_members", False),
    ("members", ("a", "b")),
    ("members_order", "alphabetical"),
    ("summary", True),
): external("602e4f55cbbc*.html"), (
    ("filters", ("a",)),
    ("inherited_members", False),
    ("members", None),
    ("members_order", "alphabetical"),
    ("summary", False),
): external("cc2b8de22380*.html"), (
    ("filters", ()),
    ("inherited_members", ()),
    ("members", False),
    ("members_order", "source"),
    ("summary", False),
): external("8d439c3179e0*.html"), (
    ("filters", ("!a",)),
    ("inherited_members", True),
    ("members", ("a", "b")),
    ("members_order", "alphabetical"),
    ("summary", False),
): external("309e711def29*.html"), (
    ("filters", None),
    ("inherited_members", True),
    ("members", ()),
    ("members_order", "alphabetical"),
    ("summary", False),
): external("f78d11ca8c95*.html"), (
    ("filters", ("!a",)),
    ("inherited_members", ()),
    ("members", False),
    ("members_order", "source"),
    ("summary", True),
): external("f49622e0aa19*.html"), (
    ("filters", ("!a",)),
    ("inherited_members", ()),
    ("members", ()),
    ("members_order", "source"),
    ("summary", True),
): external("0da131b280c2*.html"), (
    ("filters", ()),
    ("inherited_members", False),
    ("members", None),
    ("members_order", "source"),
    ("summary", True),
): external("1f5a502a27ac*.html"), (
    ("filters", ("a",)),
    ("inherited_members", True),
    ("members", True),
    ("members_order", "source"),
    ("summary", False),
): external("ebd7dfb69c2f*.html"), (
    ("filters", ("a",)),
    ("inherited_members", ("a", "b")),
    ("members", None),
    ("members_order", "source"),
    ("summary", True),
): external("43f49e0b3d6b*.html"), (
    ("filters", ("a",)),
    ("inherited_members", ("a", "b")),
    ("members", True),
    ("members_order", "alphabetical"),
    ("summary", False),
): external("b16c391b3c90*.html"), (
    ("filters", ("a",)),
    ("inherited_members", False),
    ("members", None),
    ("members_order", "source"),
    ("summary", False),
): external("769703e6ce34*.html"), (
    ("filters", ("a",)),
    ("inherited_members", ()),
    ("members", None),
    ("members_order", "source"),
    ("summary", True),
): external("d93307d86394*.html"), (
    ("filters", ("!a",)),
    ("inherited_members", ()),
    ("members", ("a", "b")),
    ("members_order", "alphabetical"),
    ("summary", False),
): external("22c7c45e7d36*.html"), (
    ("filters", ("!a",)),
    ("inherited_members", True),
    ("members", False),
    ("members_order", "source"),
    ("summary", False),
): external("c2dcad354b75*.html"), (
    ("filters", ("!a",)),
    ("inherited_members", ("a", "b")),
    ("members", True),
    ("members_order", "source"),
    ("summary", True),
): external("04c7f0ef7e14*.html"), (
    ("filters", ("a",)),
    ("inherited_members", ()),
    ("members", ()),
    ("members_order", "alphabetical"),
    ("summary", True),
): external("77ab48ad3111*.html"), (
    ("filters", None),
    ("inherited_members", ()),
    ("members", None),
    ("members_order", "alphabetical"),
    ("summary", False),
): external("93432d847cd3*.html"), (
    ("filters", ("a",)),
    ("inherited_members", True),
    ("members", ()),
    ("members_order", "alphabetical"),
    ("summary", False),
): external("9d87d539525c*.html"), (
    ("filters", ()),
    ("inherited_members", False),
    ("members", True),
    ("members_order", "alphabetical"),
    ("summary", True),
): external("823dd15e8c85*.html"), (
    ("filters", ("!a",)),
    ("inherited_members", True),
    ("members", ()),
    ("members_order", "source"),
    ("summary", True),
): external("d63e2eb6fad6*.html"), (
    ("filters", None),
    ("inherited_members", False),
    ("members", ("a", "b")),
    ("members_order", "alphabetical"),
    ("summary", False),
): external("888908f4011b*.html"), (
    ("filters", ()),
    ("inherited_members", True),
    ("members", False),
    ("members_order", "source"),
    ("summary", True),
): external("d57c35cf91f5*.html"), (
    ("filters", ()),
    ("inherited_members", ()),
    ("members", False),
    ("members_order", "alphabetical"),
    ("summary", False),
): external("958b6d9241e1*.html"), (
    ("filters", None),
    ("inherited_members", True),
    ("members", False),
    ("members_order", "alphabetical"),
    ("summary", True),
): external("47917dd7e514*.html"), (
    ("filters", ("!a",)),
    ("inherited_members", ()),
    ("members", True),
    ("members_order", "source"),
    ("summary", True),
): external("0f8184f7f44e*.html"), (
    ("filters", None),
    ("inherited_members", ("a", "b")),
    ("members", False),
    ("members_order", "source"),
    ("summary", False),
): external("b2ff69b92983*.html"), (
    ("filters", ("!a",)),
    ("inherited_members", ("a", "b")),
    ("members", True),
    ("members_order", "alphabetical"),
    ("summary", False),
): external("285b8a41a35e*.html"), (
    ("filters", None),
    ("inherited_members", False),
    ("members", ()),
    ("members_order", "source"),
    ("summary", True),
): external("9fa236b20e16*.html"), (
    ("filters", ("a",)),
    ("inherited_members", ()),
    ("members", False),
    ("members_order", "source"),
    ("summary", False),
): external("1d96ae36bbed*.html"), (
    ("filters", ("!a",)),
    ("inherited_members", True),
    ("members", False),
    ("members_order", "source"),
    ("summary", True),
): external("0df2a7282e6b*.html"), (
    ("filters", ("a",)),
    ("inherited_members", ()),
    ("members", False),
    ("members_order", "alphabetical"),
    ("summary", False),
): external("98fe74ec067b*.html"), (
    ("filters", ("!a",)),
    ("inherited_members", False),
    ("members", None),
    ("members_order", "alphabetical"),
    ("summary", False),
): external("2290ed951031*.html"), (
    ("filters", ("!a",)),
    ("inherited_members", ("a", "b")),
    ("members", ()),
    ("members_order", "source"),
    ("summary", False),
): external("5ebea0f65c7f*.html"), (
    ("filters", ("!a",)),
    ("inherited_members", ("a", "b")),
    ("members", ("a", "b")),
    ("members_order", "alphabetical"),
    ("summary", False),
): external("69663cf42bde*.html"), (
    ("filters", None),
    ("inherited_members", ("a", "b")),
    ("members", ("a", "b")),
    ("members_order", "alphabetical"),
    ("summary", False),
): external("462f61781046*.html"), (
    ("filters", ("!a",)),
    ("inherited_members", True),
    ("members", ()),
    ("members_order", "alphabetical"),
    ("summary", False),
): external("3b78bb4d0ebb*.html"), (
    ("filters", ("!a",)),
    ("inherited_members", ("a", "b")),
    ("members", ("a", "b")),
    ("members_order", "source"),
    ("summary", False),
): external("a78890c9b6a2*.html"), (
    ("filters", ("a",)),
    ("inherited_members", ()),
    ("members", ()),
    ("members_order", "source"),
    ("summary", False),
): external("2c5606e017c5*.html"), (
    ("filters", ("a",)),
    ("inherited_members", True),
    ("members", None),
    ("members_order", "source"),
    ("summary", False),
): external("24a0fce8dec1*.html"), (
    ("filters", None),
    ("inherited_members", True),
    ("members", ("a", "b")),
    ("members_order", "source"),
    ("summary", False),
): external("5c3dbbce17e6*.html"), (
    ("filters", None),
    ("inherited_members", False),
    ("members", True),
    ("members_order", "source"),
    ("summary", False),
): external("7e5754a23120*.html"), (
    ("filters", ("a",)),
    ("inherited_members", False),
    ("members", False),
    ("members_order", "source"),
    ("summary", False),
): external("c734a63d50ff*.html"), (
    ("filters", ()),
    ("inherited_members", ("a", "b")),
    ("members", False),
    ("members_order", "source"),
    ("summary", False),
): external("d3c05af740fe*.html"), (
    ("filters", None),
    ("inherited_members", ()),
    ("members", True),
    ("members_order", "source"),
    ("summary", False),
): external("f95ece9d2bcc*.html"), (
    ("filters", ()),
    ("inherited_members", ()),
    ("members", ()),
    ("members_order", "source"),
    ("summary", True),
): external("cdfc8fdb67ad*.html"), (
    ("filters", ("!a",)),
    ("inherited_members", False),
    ("members", ("a", "b")),
    ("members_order", "source"),
    ("summary", True),
): external("def8ff91ce60*.html"), (
    ("filters", ()),
    ("inherited_members", ()),
    ("members", None),
    ("members_order", "alphabetical"),
    ("summary", False),
): external("918d696365b0*.html"), (
    ("filters", None),
    ("inherited_members", True),
    ("members", ()),
    ("members_order", "alphabetical"),
    ("summary", True),
): external("89ec015daa99*.html"), (
    ("filters", ("!a",)),
    ("inherited_members", False),
    ("members", ("a", "b")),
    ("members_order", "source"),
    ("summary", False),
): external("bbb6dbd0573c*.html"), (
    ("filters", ()),
    ("inherited_members", ("a", "b")),
    ("members", False),
    ("members_order", "source"),
    ("summary", True),
): external("2a5bcde0dd1c*.html"), (
    ("filters", None),
    ("inherited_members", False),
    ("members", None),
    ("members_order", "alphabetical"),
    ("summary", True),
): external("4b5877261109*.html"), (
    ("filters", ()),
    ("inherited_members", True),
    ("members", ("a", "b")),
    ("members_order", "alphabetical"),
    ("summary", False),
): external("f46afa71b6e6*.html"), (
    ("filters", ("a",)),
    ("inherited_members", False),
    ("members", False),
    ("members_order", "alphabetical"),
    ("summary", False),
): external("ddcc438ec023*.html"), (
    ("filters", ("a",)),
    ("inherited_members", True),
    ("members", ("a", "b")),
    ("members_order", "alphabetical"),
    ("summary", True),
): external("580221623fdb*.html"), (
    ("filters", ("a",)),
    ("inherited_members", ()),
    ("members", True),
    ("members_order", "source"),
    ("summary", True),
): external("73bf814ca7a2*.html"), (
    ("filters", ()),
    ("inherited_members", ()),
    ("members", None),
    ("members_order", "alphabetical"),
    ("summary", True),
): external("b12a2d245861*.html"), (
    ("filters", ("a",)),
    ("inherited_members", False),
    ("members", False),
    ("members_order", "source"),
    ("summary", True),
): external("b7147a7e7825*.html"), (
    ("filters", ("a",)),
    ("inherited_members", ("a", "b")),
    ("members", None),
    ("members_order", "alphabetical"),
    ("summary", True),
): external("2988ec8d56e1*.html"), (
    ("filters", None),
    ("inherited_members", ()),
    ("members", None),
    ("members_order", "alphabetical"),
    ("summary", True),
): external("f5943b5bc329*.html"), (
    ("filters", ()),
    ("inherited_members", ()),
    ("members", True),
    ("members_order", "alphabetical"),
    ("summary", True),
): external("f1936f8afe63*.html"), (
    ("filters", ("a",)),
    ("inherited_members", True),
    ("members", ()),
    ("members_order", "source"),
    ("summary", False),
): external("9e66b5af3a27*.html"), (
    ("filters", ()),
    ("inherited_members", True),
    ("members", True),
    ("members_order", "source"),
    ("summary", True),
): external("106fc2724e79*.html"), (
    ("filters", ("!a",)),
    ("inherited_members", True),
    ("members", True),
    ("members_order", "alphabetical"),
    ("summary", False),
): external("5ba55b786d8c*.html"), (
    ("filters", ("!a",)),
    ("inherited_members", ("a", "b")),
    ("members", None),
    ("members_order", "alphabetical"),
    ("summary", True),
): external("78379be98187*.html"), (
    ("filters", None),
    ("inherited_members", ("a", "b")),
    ("members", False),
    ("members_order", "alphabetical"),
    ("summary", True),
): external("be2be1a0839c*.html"), (
    ("filters", ()),
    ("inherited_members", ()),
    ("members", True),
    ("members_order", "source"),
    ("summary", False),
): external("21e6aec9afc7*.html"), (
    ("filters", ("!a",)),
    ("inherited_members", False),
    ("members", False),
    ("members_order", "alphabetical"),
    ("summary", False),
): external("ff0be12771d1*.html"), (
    ("filters", ()),
    ("inherited_members", True),
    ("members", ()),
    ("members_order", "alphabetical"),
    ("summary", True),
): external("e7a66256acd1*.html"), (
    ("filters", None),
    ("inherited_members", ()),
    ("members", ()),
    ("members_order", "alphabetical"),
    ("summary", True),
): external("e7f5e907aeab*.html"), (
    ("filters", ("a",)),
    ("inherited_members", ()),
    ("members", ("a", "b")),
    ("members_order", "source"),
    ("summary", True),
): external("3ed67588c3d7*.html"), (
    ("filters", None),
    ("inherited_members", False),
    ("members", None),
    ("members_order", "source"),
    ("summary", True),
): external("bb1f38b0b402*.html"), (
    ("filters", ()),
    ("inherited_members", True),
    ("members", False),
    ("members_order", "alphabetical"),
    ("summary", False),
): external("c2c40aa8bdb1*.html"), (
    ("filters", None),
    ("inherited_members", ("a", "b")),
    ("members", None),
    ("members_order", "source"),
    ("summary", False),
): external("87ae5ec56930*.html"), (
    ("filters", ()),
    ("inherited_members", ()),
    ("members", ()),
    ("members_order", "source"),
    ("summary", False),
): external("54e530d1d8ce*.html"), (
    ("filters", ("!a",)),
    ("inherited_members", False),
    ("members", ()),
    ("members_order", "source"),
    ("summary", False),
): external("e9ac1264c113*.html"), (
    ("filters", ("a",)),
    ("inherited_members", True),
    ("members", ("a", "b")),
    ("members_order", "source"),
    ("summary", True),
): external("8fbf6ff1bc16*.html"), (
    ("filters", ("a",)),
    ("inherited_members", ()),
    ("members", True),
    ("members_order", "source"),
    ("summary", False),
): external("55b45104ebea*.html"), (
    ("filters", ("!a",)),
    ("inherited_members", ("a", "b")),
    ("members", False),
    ("members_order", "alphabetical"),
    ("summary", True),
): external("f97d0186d988*.html"), (
    ("filters", ("a",)),
    ("inherited_members", True),
    ("members", False),
    ("members_order", "alphabetical"),
    ("summary", False),
): external("8d73cafcd039*.html"), (
    ("filters", ("a",)),
    ("inherited_members", ("a", "b")),
    ("members", ()),
    ("members_order", "alphabetical"),
    ("summary", True),
): external("f1ca5b8f4c67*.html"), (
    ("filters", ()),
    ("inherited_members", False),
    ("members", False),
    ("members_order", "alphabetical"),
    ("summary", True),
): external("979493649b87*.html"), (
    ("filters", ("a",)),
    ("inherited_members", ()),
    ("members", False),
    ("members_order", "source"),
    ("summary", True),
): external("16ae82335336*.html"), (
    ("filters", None),
    ("inherited_members", False),
    ("members", None),
    ("members_order", "alphabetical"),
    ("summary", False),
): external("cf2b4ef1e214*.html"), (
    ("filters", ("a",)),
    ("inherited_members", False),
    ("members", ()),
    ("members_order", "alphabetical"),
    ("summary", False),
): external("f4124fa705d0*.html"), (
    ("filters", ("a",)),
    ("inherited_members", True),
    ("members", ()),
    ("members_order", "alphabetical"),
    ("summary", True),
): external("49d4892a344d*.html"), (
    ("filters", ("!a",)),
    ("inherited_members", ()),
    ("members", ("a", "b")),
    ("members_order", "alphabetical"),
    ("summary", True),
): external("12b1355daeb1*.html"), (
    ("filters", ()),
    ("inherited_members", False),
    ("members", ("a", "b")),
    ("members_order", "alphabetical"),
    ("summary", True),
): external("f8a35696c136*.html"), (
    ("filters", ("!a",)),
    ("inherited_members", True),
    ("members", False),
    ("members_order", "alphabetical"),
    ("summary", True),
): external("8a94306c8e8e*.html"), (
    ("filters", ("!a",)),
    ("inherited_members", ("a", "b")),
    ("members", ()),
    ("members_order", "source"),
    ("summary", True),
): external("877efd0ec2f1*.html"), (
    ("filters", None),
    ("inherited_members", True),
    ("members", None),
    ("members_order", "source"),
    ("summary", True),
): external("f6714928c87e*.html"), (
    ("filters", ("a",)),
    ("inherited_members", ()),
    ("members", None),
    ("members_order", "alphabetical"),
    ("summary", False),
): external("57aa91a23738*.html"), (
    ("filters", ("!a",)),
    ("inherited_members", ()),
    ("members", False),
    ("members_order", "alphabetical"),
    ("summary", True),
): external("5d93ada32964*.html"), (
    ("filters", ()),
    ("inherited_members", True),
    ("members", None),
    ("members_order", "source"),
    ("summary", False),
): external("560a4935b00a*.html"), (
    ("filters", ("a",)),
    ("inherited_members", ()),
    ("members", ("a", "b")),
    ("members_order", "alphabetical"),
    ("summary", True),
): external("3d7b25eccc05*.html"), (
    ("filters", ("a",)),
    ("inherited_members", True),
    ("members", True),
    ("members_order", "source"),
    ("summary", True),
): external("9e71a450d587*.html"), (
    ("filters", ("a",)),
    ("inherited_members", ("a", "b")),
    ("members", ()),
    ("members_order", "alphabetical"),
    ("summary", False),
): external("b5366da246f1*.html"), (
    ("filters", ("a",)),
    ("inherited_members", ()),
    ("members", True),
    ("members_order", "alphabetical"),
    ("summary", False),
): external("f3885d5b99af*.html"), (
    ("filters", None),
    ("inherited_members", True),
    ("members", ("a", "b")),
    ("members_order", "source"),
    ("summary", True),
): external("c5d7dbf200d4*.html"), (
    ("filters", ("a",)),
    ("inherited_members", ()),
    ("members", ()),
    ("members_order", "source"),
    ("summary", True),
): external("363123a405bf*.html"), (
    ("filters", ("a",)),
    ("inherited_members", False),
    ("members", True),
    ("members_order", "source"),
    ("summary", True),
): external("6919dd2b2a19*.html"), (
    ("filters", ("!a",)),
    ("inherited_members", True),
    ("members", ("a", "b")),
    ("members_order", "source"),
    ("summary", False),
): external("2a742bb3aa10*.html"), (
    ("filters", ("!a",)),
    ("inherited_members", ("a", "b")),
    ("members", ("a", "b")),
    ("members_order", "alphabetical"),
    ("summary", True),
): external("42ee2b134f8d*.html"), (
    ("filters", ()),
    ("inherited_members", False),
    ("members", True),
    ("members_order", "source"),
    ("summary", False),
): external("b040d80d72b7*.html"), (
    ("filters", ("!a",)),
    ("inherited_members", False),
    ("members", True),
    ("members_order", "alphabetical"),
    ("summary", False),
): external("90c7100e7019*.html"), (
    ("filters", ("a",)),
    ("inherited_members", ()),
    ("members", ("a", "b")),
    ("members_order", "alphabetical"),
    ("summary", False),
): external("ac25cc86f070*.html"), (
    ("filters", ()),
    ("inherited_members", False),
    ("members", None),
    ("members_order", "source"),
    ("summary", False),
): external("db2b73166ee6*.html"), (
    ("filters", ("a",)),
    ("inherited_members", False),
    ("members", True),
    ("members_order", "source"),
    ("summary", False),
): external("03faac0bf81f*.html"), (
    ("filters", None),
    ("inherited_members", False),
    ("members", True),
    ("members_order", "alphabetical"),
    ("summary", True),
): external("3e36f0ca6bb0*.html"), (
    ("filters", ()),
    ("inherited_members", ()),
    ("members", ("a", "b")),
    ("members_order", "alphabetical"),
    ("summary", True),
): external("6b83f84d7172*.html"), (
    ("filters", ("!a",)),
    ("inherited_members", False),
    ("members", None),
    ("members_order", "alphabetical"),
    ("summary", True),
): external("73aab2f501d0*.html"), (
    ("filters", None),
    ("inherited_members", True),
    ("members", False),
    ("members_order", "source"),
    ("summary", True),
): external("d0cc6817d31e*.html"), (
    ("filters", None),
    ("inherited_members", True),
    ("members", True),
    ("members_order", "alphabetical"),
    ("summary", False),
): external("24f15c35708d*.html"), (
    ("filters", ()),
    ("inherited_members", ()),
    ("members", True),
    ("members_order", "source"),
    ("summary", True),
): external("c73ded676636*.html"), (
    ("filters", ("!a",)),
    ("inherited_members", ("a", "b")),
    ("members", ()),
    ("members_order", "alphabetical"),
    ("summary", True),
): external("92d1e9999cfd*.html"), (
    ("filters", ("a",)),
    ("inherited_members", True),
    ("members", True),
    ("members_order", "alphabetical"),
    ("summary", True),
): external("3d8fd453ffc7*.html"), (
    ("filters", ()),
    ("inherited_members", ()),
    ("members", True),
    ("members_order", "alphabetical"),
    ("summary", False),
): external("dcba61bc6c25*.html"), (
    ("filters", None),
    ("inherited_members", True),
    ("members", None),
    ("members_order", "alphabetical"),
    ("summary", True),
): external("22994b29618a*.html"), (
    ("filters", ("a",)),
    ("inherited_members", False),
    ("members", None),
    ("members_order", "source"),
    ("summary", True),
): external("98998f322ca1*.html"), (
    ("filters", ("!a",)),
    ("inherited_members", ()),
    ("members", None),
    ("members_order", "alphabetical"),
    ("summary", False),
): external("32f3f81fc1c9*.html"), (
    ("filters", ()),
    ("inherited_members", False),
    ("members", False),
    ("members_order", "source"),
    ("summary", True),
): external("dfd1a6385ded*.html"), (
    ("filters", None),
    ("inherited_members", ("a", "b")),
    ("members", False),
    ("members_order", "source"),
    ("summary", True),
): external("3cb2395fad1b*.html"), (
    ("filters", ()),
    ("inherited_members", True),
    ("members", ("a", "b")),
    ("members_order", "alphabetical"),
    ("summary", True),
): external("f304a2cd565d*.html"), (
    ("filters", ()),
    ("inherited_members", ()),
    ("members", None),
    ("members_order", "source"),
    ("summary", False),
): external("93728436425a*.html"), (
    ("filters", None),
    ("inherited_members", ()),
    ("members", False),
    ("members_order", "source"),
    ("summary", False),
): external("116c375b5c53*.html"), (
    ("filters", ("!a",)),
    ("inherited_members", False),
    ("members", ()),
    ("members_order", "alphabetical"),
    ("summary", True),
): external("70208fdd0425*.html"), (
    ("filters", ("a",)),
    ("inherited_members", False),
    ("members", ()),
    ("members_order", "alphabetical"),
    ("summary", True),
): external("63e3a937fca4*.html"), (
    ("filters", None),
    ("inherited_members", ()),
    ("members", True),
    ("members_order", "alphabetical"),
    ("summary", False),
): external("81c0c5c4f47b*.html"), (
    ("filters", ("a",)),
    ("inherited_members", ("a", "b")),
    ("members", True),
    ("members_order", "source"),
    ("summary", True),
): external("b26de916cbd1*.html"), (
    ("filters", ()),
    ("inherited_members", ("a", "b")),
    ("members", True),
    ("members_order", "source"),
    ("summary", False),
): external("bce48b084c18*.html"), (
    ("filters", ("!a",)),
    ("inherited_members", ()),
    ("members", False),
    ("members_order", "source"),
    ("summary", False),
): external("3f7b293cd997*.html"), (
    ("filters", ("!a",)),
    ("inherited_members", True),
    ("members", ("a", "b")),
    ("members_order", "source"),
    ("summary", True),
): external("ca2142c3fcf4*.html"), (
    ("filters", ("!a",)),
    ("inherited_members", True),
    ("members", True),
    ("members_order", "source"),
    ("summary", False),
): external("0ec08db05e14*.html"), (
    ("filters", ()),
    ("inherited_members", False),
    ("members", None),
    ("members_order", "alphabetical"),
    ("summary", False),
): external("48fa5bfde628*.html"), (
    ("filters", ("a",)),
    ("inherited_members", True),
    ("members", None),
    ("members_order", "alphabetical"),
    ("summary", True),
): external("0223ae2b9ec3*.html"), (
    ("filters", ()),
    ("inherited_members", ("a", "b")),
    ("members", ("a", "b")),
    ("members_order", "alphabetical"),
    ("summary", False),
): external("89eda4db2439*.html"), (
    ("filters", ("!a",)),
    ("inherited_members", ("a", "b")),
    ("members", None),
    ("members_order", "source"),
    ("summary", False),
): external("4776219b833e*.html"), (
    ("filters", ()),
    ("inherited_members", ("a", "b")),
    ("members", True),
    ("members_order", "source"),
    ("summary", True),
): external("b577e0f004dc*.html"), (
    ("filters", None),
    ("inherited_members", True),
    ("members", ()),
    ("members_order", "source"),
    ("summary", True),
): external("ad282e51c3e1*.html"), (
    ("filters", None),
    ("inherited_members", ("a", "b")),
    ("members", True),
    ("members_order", "alphabetical"),
    ("summary", True),
): external("644db050b54c*.html"), (
    ("filters", ("a",)),
    ("inherited_members", False),
    ("members", ("a", "b")),
    ("members_order", "alphabetical"),
    ("summary", False),
): external("e19fc62a7e80*.html"), (
    ("filters", None),
    ("inherited_members", ()),
    ("members", False),
    ("members_order", "alphabetical"),
    ("summary", True),
): external("c9edc30f7f98*.html"), (
    ("filters", ()),
    ("inherited_members", True),
    ("members", True),
    ("members_order", "source"),
    ("summary", False),
): external("931af6492fa0*.html"), (
    ("filters", ("a",)),
    ("inherited_members", False),
    ("members", ("a", "b")),
    ("members_order", "source"),
    ("summary", True),
): external("c82eab961339*.html"), (
    ("filters", ("a",)),
    ("inherited_members", ()),
    ("members", False),
    ("members_order", "alphabetical"),
    ("summary", True),
): external("aa4eb42695be*.html"), (
    ("filters", None),
    ("inherited_members", ()),
    ("members", ()),
    ("members_order", "source"),
    ("summary", False),
): external("33d35c58796a*.html"), (
    ("filters", ("!a",)),
    ("inherited_members", ()),
    ("members", ()),
    ("members_order", "source"),
    ("summary", False),
): external("81baf3c92cc4*.html"), (
    ("filters", None),
    ("inherited_members", ("a", "b")),
    ("members", True),
    ("members_order", "alphabetical"),
    ("summary", False),
): external("9fc801c5ecf8*.html"), (
    ("filters", None),
    ("inherited_members", ("a", "b")),
    ("members", False),
    ("members_order", "alphabetical"),
    ("summary", False),
): external("cff5b9e85888*.html"), (
    ("filters", None),
    ("inherited_members", False),
    ("members", ()),
    ("members_order", "source"),
    ("summary", False),
): external("089ec75fd1ea*.html"), (
    ("filters", ("!a",)),
    ("inherited_members", True),
    ("members", True),
    ("members_order", "source"),
    ("summary", True),
): external("509ad5c7a35e*.html"), (
    ("filters", None),
    ("inherited_members", False),
    ("members", False),
    ("members_order", "source"),
    ("summary", True),
): external("538f016575ba*.html"), (
    ("filters", None),
    ("inherited_members", True),
    ("members", ("a", "b")),
    ("members_order", "alphabetical"),
    ("summary", False),
): external("c1cc13c39382*.html"), (
    ("filters", ()),
    ("inherited_members", False),
    ("members", ()),
    ("members_order", "alphabetical"),
    ("summary", False),
): external("594f01aaecff*.html"), (
    ("filters", ("!a",)),
    ("inherited_members", ("a", "b")),
    ("members", True),
    ("members_order", "source"),
    ("summary", False),
): external("4ed6b0b6bd9d*.html"), (
    ("filters", ("!a",)),
    ("inherited_members", False),
    ("members", False),
    ("members_order", "source"),
    ("summary", True),
): external("7070a112fc2e*.html"), (
    ("filters", ()),
    ("inherited_members", True),
    ("members", ()),
    ("members_order", "alphabetical"),
    ("summary", False),
): external("a8b3ac219186*.html"), (
    ("filters", None),
    ("inherited_members", ("a", "b")),
    ("members", ()),
    ("members_order", "alphabetical"),
    ("summary", True),
): external("def7ed2c67af*.html"), (
    ("filters", None),
    ("inherited_members", ()),
    ("members", ()),
    ("members_order", "source"),
    ("summary", True),
): external("cf6856baced1*.html"), (
    ("filters", ()),
    ("inherited_members", False),
    ("members", ("a", "b")),
    ("members_order", "source"),
    ("summary", True),
): external("e186fac539ed*.html"), (
    ("filters", None),
    ("inherited_members", ()),
    ("members", True),
    ("members_order", "alphabetical"),
    ("summary", True),
): external("074218e5af63*.html"), (
    ("filters", ()),
    ("inherited_members", False),
    ("members", True),
    ("members_order", "source"),
    ("summary", True),
): external("9d3cbc4f5478*.html"), (
    ("filters", None),
    ("inherited_members", ("a", "b")),
    ("members", None),
    ("members_order", "source"),
    ("summary", True),
): external("b3db83b34932*.html"), (
    ("filters", ("a",)),
    ("inherited_members", False),
    ("members", ("a", "b")),
    ("members_order", "source"),
    ("summary", False),
): external("db662cfd8aa8*.html"), (
    ("filters", ("a",)),
    ("inherited_members", False),
    ("members", ("a", "b")),
    ("members_order", "alphabetical"),
    ("summary", True),
): external("f6ca0a28d92f*.html"), (
    ("filters", ()),
    ("inherited_members", True),
    ("members", ()),
    ("members_order", "source"),
    ("summary", False),
): external("3005e9c43523*.html"), (
    ("filters", ("!a",)),
    ("inherited_members", ()),
    ("members", True),
    ("members_order", "alphabetical"),
    ("summary", True),
): external("2a5ea295acc8*.html"), (
    ("filters", ()),
    ("inherited_members", True),
    ("members", False),
    ("members_order", "alphabetical"),
    ("summary", True),
): external("6d387970e5af*.html"), (
    ("filters", ("!a",)),
    ("inherited_members", True),
    ("members", True),
    ("members_order", "alphabetical"),
    ("summary", True),
): external("c689c37a75fa*.html"), (
    ("filters", ("!a",)),
    ("inherited_members", ("a", "b")),
    ("members", ()),
    ("members_order", "alphabetical"),
    ("summary", False),
): external("e804870f8dec*.html"), (
    ("filters", ("!a",)),
    ("inherited_members", True),
    ("members", ("a", "b")),
    ("members_order", "alphabetical"),
    ("summary", True),
): external("69cefc64fbc6*.html"), (
    ("filters", ("a",)),
    ("inherited_members", ()),
    ("members", ()),
    ("members_order", "alphabetical"),
    ("summary", False),
): external("ef8abb845cef*.html"), (
    ("filters", None),
    ("inherited_members", True),
    ("members", False),
    ("members_order", "source"),
    ("summary", False),
): external("5d5de71a045e*.html"), (
    ("filters", ()),
    ("inherited_members", False),
    ("members", ()),
    ("members_order", "source"),
    ("summary", False),
): external("6db9c7e15117*.html"), (
    ("filters", None),
    ("inherited_members", True),
    ("members", True),
    ("members_order", "source"),
    ("summary", False),
): external("f62544a1d996*.html"), (
    ("filters", ("a",)),
    ("inherited_members", True),
    ("members", None),
    ("members_order", "alphabetical"),
    ("summary", False),
): external("3d272f781c39*.html"), (
    ("filters", ()),
    ("inherited_members", True),
    ("members", None),
    ("members_order", "alphabetical"),
    ("summary", True),
): external("43a91801f4dc*.html"), (
    ("filters", ("a",)),
    ("inherited_members", ("a", "b")),
    ("members", True),
    ("members_order", "source"),
    ("summary", False),
): external("a61783bc066c*.html"), (
    ("filters", ("!a",)),
    ("inherited_members", True),
    ("members", False),
    ("members_order", "alphabetical"),
    ("summary", False),
): external("6b67b40b3bdc*.html"), (
    ("filters", ()),
    ("inherited_members", ()),
    ("members", False),
    ("members_order", "alphabetical"),
    ("summary", True),
): external("ed7cd1986400*.html"), (
    ("filters", ()),
    ("inherited_members", ("a", "b")),
    ("members", ()),
    ("members_order", "alphabetical"),
    ("summary", True),
): external("a9b920b0f214*.html"), (
    ("filters", ()),
    ("inherited_members", ()),
    ("members", ("a", "b")),
    ("members_order", "alphabetical"),
    ("summary", False),
): external("ae037f73dc3c*.html"), (
    ("filters", ()),
    ("inherited_members", ("a", "b")),
    ("members", None),
    ("members_order", "alphabetical"),
    ("summary", False),
): external("ce9e19920db0*.html"), (
    ("filters", None),
    ("inherited_members", ()),
    ("members", None),
    ("members_order", "source"),
    ("summary", True),
): external("86b2df1711bd*.html"), (
    ("filters", ()),
    ("inherited_members", ("a", "b")),
    ("members", None),
    ("members_order", "alphabetical"),
    ("summary", True),
): external("87f90534a6b0*.html"), (
    ("filters", ("a",)),
    ("inherited_members", True),
    ("members", ("a", "b")),
    ("members_order", "source"),
    ("summary", False),
): external("9eed80e8c869*.html"), (
    ("filters", ("a",)),
    ("inherited_members", True),
    ("members", False),
    ("members_order", "source"),
    ("summary", False),
): external("bc8b644c1e9f*.html"), (
    ("filters", None),
    ("inherited_members", ()),
    ("members", ("a", "b")),
    ("members_order", "source"),
    ("summary", True),
): external("f41033707fe3*.html"), (
    ("filters", ()),
    ("inherited_members", ("a", "b")),
    ("members", ()),
    ("members_order", "source"),
    ("summary", False),
): external("e0544f7e28fc*.html"), (
    ("filters", ()),
    ("inherited_members", True),
    ("members", None),
    ("members_order", "alphabetical"),
    ("summary", False),
): external("1d764988017b*.html"), (
    ("filters", None),
    ("inherited_members", ()),
    ("members", ("a", "b")),
    ("members_order", "alphabetical"),
    ("summary", False),
): external("f048f142bf67*.html"), (
    ("filters", ("!a",)),
    ("inherited_members", True),
    ("members", None),
    ("members_order", "source"),
    ("summary", False),
): external("f8b1f29c6ba6*.html"), (
    ("filters", None),
    ("inherited_members", ("a", "b")),
    ("members", True),
    ("members_order", "source"),
    ("summary", True),
): external("cf631252cc62*.html"), (
    ("filters", ()),
    ("inherited_members", False),
    ("members", False),
    ("members_order", "source"),
    ("summary", False),
): external("6b488f7bb1c1*.html"), (
    ("filters", ()),
    ("inherited_members", ()),
    ("members", ("a", "b")),
    ("members_order", "source"),
    ("summary", False),
): external("90658b5541f7*.html"), (
    ("filters", ("a",)),
    ("inherited_members", False),
    ("members", ()),
    ("members_order", "source"),
    ("summary", True),
): external("87917dd63369*.html"), (
    ("filters", ("a",)),
    ("inherited_members", ("a", "b")),
    ("members", False),
    ("members_order", "source"),
    ("summary", True),
): external("324a62c0bb53*.html"), (
    ("filters", ("a",)),
    ("inherited_members", ()),
    ("members", ("a", "b")),
    ("members_order", "source"),
    ("summary", False),
): external("70a58026f652*.html"), (
    ("filters", ()),
    ("inherited_members", ()),
    ("members", ()),
    ("members_order", "alphabetical"),
    ("summary", True),
): external("5f33ac3a8ee5*.html"), (
    ("filters", ("!a",)),
    ("inherited_members", ("a", "b")),
    ("members", False),
    ("members_order", "source"),
    ("summary", False),
): external("e3181c25f95f*.html"), (
    ("filters", None),
    ("inherited_members", ("a", "b")),
    ("members", ("a", "b")),
    ("members_order", "source"),
    ("summary", True),
): external("fdb9ce603db1*.html"), (
    ("filters", ("!a",)),
    ("inherited_members", ()),
    ("members", ("a", "b")),
    ("members_order", "source"),
    ("summary", True),
): external("fbb4ade16846*.html"), (
    ("filters", ("a",)),
    ("inherited_members", ("a", "b")),
    ("members", ("a", "b")),
    ("members_order", "source"),
    ("summary", False),
): external("0ff8a0d36695*.html"), (
    ("filters", ()),
    ("inherited_members", ("a", "b")),
    ("members", False),
    ("members_order", "alphabetical"),
    ("summary", False),
): external("7a384683f3be*.html"), (
    ("filters", ()),
    ("inherited_members", ()),
    ("members", False),
    ("members_order", "source"),
    ("summary", True),
): external("70bcc717c353*.html"), (
    ("filters", ("!a",)),
    ("inherited_members", False),
    ("members", ("a", "b")),
    ("members_order", "alphabetical"),
    ("summary", False),
): external("5884aaf100b2*.html"), (
    ("filters", ("!a",)),
    ("inherited_members", ("a", "b")),
    ("members", False),
    ("members_order", "source"),
    ("summary", True),
): external("1dd6e42a99b9*.html"), (
    ("filters", None),
    ("inherited_members", False),
    ("members", ()),
    ("members_order", "alphabetical"),
    ("summary", False),
): external("a11717a3e672*.html"), (
    ("filters", ()),
    ("inherited_members", False),
    ("members", False),
    ("members_order", "alphabetical"),
    ("summary", False),
): external("2d8fe79afdac*.html"), (
    ("filters", None),
    ("inherited_members", ()),
    ("members", False),
    ("members_order", "source"),
    ("summary", True),
): external("840d5a1078e0*.html"), (
    ("filters", None),
    ("inherited_members", False),
    ("members", False),
    ("members_order", "alphabetical"),
    ("summary", False),
): external("a0ad905ddd30*.html"), (
    ("filters", ()),
    ("inherited_members", ("a", "b")),
    ("members", ("a", "b")),
    ("members_order", "source"),
    ("summary", False),
): external("ca508ebe90dd*.html"), (
    ("filters", None),
    ("inherited_members", False),
    ("members", ("a", "b")),
    ("members_order", "source"),
    ("summary", True),
): external("48eb97267fdb*.html"), (
    ("filters", ("!a",)),
    ("inherited_members", False),
    ("members", True),
    ("members_order", "alphabetical"),
    ("summary", True),
): external("ffa45b36b713*.html"), (
    ("filters", None),
    ("inherited_members", ()),
    ("members", None),
    ("members_order", "source"),
    ("summary", False),
): external("8c3b86e911b1*.html"), (
    ("filters", None),
    ("inherited_members", False),
    ("members", ("a", "b")),
    ("members_order", "alphabetical"),
    ("summary", True),
): external("a58d47cb19fb*.html"), (
    ("filters", ("!a",)),
    ("inherited_members", ()),
    ("members", ()),
    ("members_order", "alphabetical"),
    ("summary", False),
): external("d9af88598a6a*.html"), (
    ("filters", None),
    ("inherited_members", False),
    ("members", True),
    ("members_order", "alphabetical"),
    ("summary", False),
): external("7a84ff956a3a*.html"), (
    ("filters", ("!a",)),
    ("inherited_members", ("a", "b")),
    ("members", None),
    ("members_order", "source"),
    ("summary", True),
): external("a3cf958032f2*.html"), (
    ("filters", None),
    ("inherited_members", True),
    ("members", None),
    ("members_order", "alphabetical"),
    ("summary", False),
): external("7b40bc090c5f*.html"), (
    ("filters", None),
    ("inherited_members", False),
    ("members", ()),
    ("members_order", "alphabetical"),
    ("summary", True),
): external("0ab728c18038*.html"), (
    ("filters", ("!a",)),
    ("inherited_members", False),
    ("members", None),
    ("members_order", "source"),
    ("summary", False),
): external("3fe67fd5609e*.html"), (
    ("filters", ()),
    ("inherited_members", False),
    ("members", ("a", "b")),
    ("members_order", "source"),
    ("summary", False),
): external("a34470229e5c*.html"), (
    ("filters", ("!a",)),
    ("inherited_members", False),
    ("members", ()),
    ("members_order", "alphabetical"),
    ("summary", False),
): external("991c374cd8f0*.html"), (
    ("filters", ("!a",)),
    ("inherited_members", ()),
    ("members", ()),
    ("members_order", "alphabetical"),
    ("summary", True),
): external("f5be86772b11*.html"), (
    ("filters", None),
    ("inherited_members", ("a", "b")),
    ("members", ()),
    ("members_order", "source"),
    ("summary", True),
): external("3898afa24378*.html"), (
    ("filters", ("a",)),
    ("inherited_members", ("a", "b")),
    ("members", False),
    ("members_order", "alphabetical"),
    ("summary", True),
): external("53bd078c1c97*.html"), (
    ("filters", None),
    ("inherited_members", ("a", "b")),
    ("members", None),
    ("members_order", "alphabetical"),
    ("summary", False),
): external("63b1c2447ec6*.html"), (
    ("filters", ("!a",)),
    ("inherited_members", True),
    ("members", None),
    ("members_order", "alphabetical"),
    ("summary", False),
): external("420ac029f4e1*.html"), (
    ("filters", ("a",)),
    ("inherited_members", True),
    ("members", False),
    ("members_order", "source"),
    ("summary", True),
): external("36005432c62e*.html"), (
    ("filters", None),
    ("inherited_members", ("a", "b")),
    ("members", None),
    ("members_order", "alphabetical"),
    ("summary", True),
): external("4155c43c1f14*.html"), (
    ("filters", None),
    ("inherited_members", True),
    ("members", True),
    ("members_order", "source"),
    ("summary", True),
): external("73687903324f*.html"), (
    ("filters", None),
    ("inherited_members", ()),
    ("members", ("a", "b")),
    ("members_order", "alphabetical"),
    ("summary", True),
): external("0bdb938df471*.html"), (
    ("filters", ()),
    ("inherited_members", False),
    ("members", ("a", "b")),
    ("members_order", "alphabetical"),
    ("summary", False),
): external("4e7ac599f0e1*.html"), (
    ("filters", None),
    ("inherited_members", ()),
    ("members", ("a", "b")),
    ("members_order", "source"),
    ("summary", False),
): external("df8df06bd8bc*.html"), (
    ("filters", ("!a",)),
    ("inherited_members", ("a", "b")),
    ("members", False),
    ("members_order", "alphabetical"),
    ("summary", False),
): external("062257fc0f7f*.html"), (
    ("filters", ("a",)),
    ("inherited_members", ("a", "b")),
    ("members", None),
    ("members_order", "source"),
    ("summary", False),
): external("4775574fb7ab*.html"), (
    ("filters", ("a",)),
    ("inherited_members", ("a", "b")),
    ("members", ("a", "b")),
    ("members_order", "alphabetical"),
    ("summary", True),
): external("0ac4a37dafe2*.html"), (
    ("filters", None),
    ("inherited_members", True),
    ("members", None),
    ("members_order", "source"),
    ("summary", False),
): external("088500a74d92*.html"), (
    ("filters", None),
    ("inherited_members", False),
    ("members", False),
    ("members_order", "source"),
    ("summary", False),
): external("6cf2fc007996*.html"), (
    ("filters", ("!a",)),
    ("inherited_members", ()),
    ("members", False),
    ("members_order", "alphabetical"),
    ("summary", False),
): external("2680157aee5d*.html"), (
    ("filters", ()),
    ("inherited_members", True),
    ("members", ()),
    ("members_order", "source"),
    ("summary", True),
): external("04ec817a8e7f*.html"), (
    ("filters", ("!a",)),
    ("inherited_members", False),
    ("members", False),
    ("members_order", "source"),
    ("summary", False),
): external("33908fa7851e*.html"), (
    ("filters", None),
    ("inherited_members", True),
    ("members", True),
    ("members_order", "alphabetical"),
    ("summary", True),
): external("bfb70c82a4dd*.html"), (
    ("filters", ("a",)),
    ("inherited_members", False),
    ("members", ()),
    ("members_order", "source"),
    ("summary", False),
): external("deb1ad7c569c*.html"), (
    ("filters", None),
    ("inherited_members", True),
    ("members", False),
    ("members_order", "alphabetical"),
    ("summary", False),
): external("53a4d683d951*.html"), (
    ("filters", ()),
    ("inherited_members", False),
    ("members", None),
    ("members_order", "alphabetical"),
    ("summary", True),
): external("b0c97e841467*.html"), (
    ("filters", None),
    ("inherited_members", ("a", "b")),
    ("members", ("a", "b")),
    ("members_order", "alphabetical"),
    ("summary", True),
): external("ce17e9c2bb97*.html"), (
    ("filters", ("a",)),
    ("inherited_members", ()),
    ("members", None),
    ("members_order", "source"),
    ("summary", False),
): external("23dae406ac89*.html"), (
    ("filters", ("a",)),
    ("inherited_members", False),
    ("members", False),
    ("members_order", "alphabetical"),
    ("summary", True),
): external("94b907ba4d0b*.html"), (
    ("filters", ()),
    ("inherited_members", False),
    ("members", ()),
    ("members_order", "source"),
    ("summary", True),
): external("9e82a7a3c8a5*.html"), (
    ("filters", None),
    ("inherited_members", False),
    ("members", True),
    ("members_order", "source"),
    ("summary", True),
): external("c02ddb096400*.html"), (
    ("filters", ()),
    ("inherited_members", True),
    ("members", ("a", "b")),
    ("members_order", "source"),
    ("summary", False),
): external("06a5823037c2*.html"), (
    ("filters", ()),
    ("inherited_members", ()),
    ("members", ("a", "b")),
    ("members_order", "source"),
    ("summary", True),
): external("5b3823d47a7e*.html"), (
    ("filters", None),
    ("inherited_members", False),
    ("members", False),
    ("members_order", "alphabetical"),
    ("summary", True),
): external("c4ed70d83d77*.html"), (
    ("filters", ("!a",)),
    ("inherited_members", True),
    ("members", ()),
    ("members_order", "alphabetical"),
    ("summary", True),
): external("4d15645c674f*.html"), (
    ("filters", ("a",)),
    ("inherited_members", ("a", "b")),
    ("members", ("a", "b")),
    ("members_order", "source"),
    ("summary", True),
): external("c2ee733eb848*.html"), (
    ("filters", ("a",)),
    ("inherited_members", ("a", "b")),
    ("members", None),
    ("members_order", "alphabetical"),
    ("summary", False),
): external("eb83833c9204*.html"), (
    ("filters", ("!a",)),
    ("inherited_members", False),
    ("members", True),
    ("members_order", "source"),
    ("summary", True),
): external("238849911bfc*.html"), (
    ("filters", None),
    ("inherited_members", ()),
    ("members", True),
    ("members_order", "source"),
    ("summary", True),
): external("cc0811165a3c*.html"), (
    ("filters", ()),
    ("inherited_members", ("a", "b")),
    ("members", None),
    ("members_order", "source"),
    ("summary", False),
): external("bce925b03ed8*.html"), (
    ("filters", ("a",)),
    ("inherited_members", ("a", "b")),
    ("members", ()),
    ("members_order", "source"),
    ("summary", True),
): external("66f9ab1f1b31*.html"), (
    ("filters", ("a",)),
    ("inherited_members", True),
    ("members", True),
    ("members_order", "alphabetical"),
    ("summary", False),
): external("9196360b138b*.html"), (
    ("filters", ("!a",)),
    ("inherited_members", ("a", "b")),
    ("members", ("a", "b")),
    ("members_order", "source"),
    ("summary", True),
): external("d87eb28de7b3*.html"), (
    ("filters", ()),
    ("inherited_members", ("a", "b")),
    ("members", ("a", "b")),
    ("members_order", "alphabetical"),
    ("summary", True),
): external("f06ca746bc46*.html"), (
    ("filters", ()),
    ("inherited_members", ("a", "b")),
    ("members", ()),
    ("members_order", "alphabetical"),
    ("summary", False),
): external("0336aea94222*.html"), (
    ("filters", ()),
    ("inherited_members", False),
    ("members", True),
    ("members_order", "alphabetical"),
    ("summary", False),
): external("8a55ca54f9f4*.html")})


# Signature options
@pytest.mark.parametrize("annotations_path", options["annotations_path"])
@pytest.mark.parametrize("show_signature", options["show_signature"])
@pytest.mark.parametrize("show_signature_annotations", options["show_signature_annotations"])
@pytest.mark.parametrize("signature_crossrefs", options["signature_crossrefs"])
@pytest.mark.parametrize("separate_signature", options["separate_signature"])
@pytest.mark.parametrize("unwrap_annotated", options["unwrap_annotated"])
def test_end_to_end_for_signatures(
    session_handler: PythonHandler,
    annotations_path: str,
    show_signature: bool,
    show_signature_annotations: bool,
    signature_crossrefs: bool,
    separate_signature: bool,
    unwrap_annotated: bool,
) -> None:
    """Test rendering of a given theme's templates.

    Parameters:
        identifier: Parametrized identifier.
        session_handler: Python handler (fixture).
    """
    final_options = {
        "annotations_path": annotations_path,
        "show_signature": show_signature,
        "show_signature_annotations": show_signature_annotations,
        "signature_crossrefs": signature_crossrefs,
        "separate_signature": separate_signature,
        "unwrap_annotated": unwrap_annotated,
    }
    html = _render_options(final_options) + _render(session_handler, final_options)
    snapshot_key = tuple(sorted(final_options.items()))
    assert outsource(html, suffix=".html") == snapshots_signatures[snapshot_key]


# Members options.
@pytest.mark.parametrize("inherited_members", options["inherited_members"])
@pytest.mark.parametrize("members", options["members"])
@pytest.mark.parametrize("members_order", options["members_order"])
@pytest.mark.parametrize("filters", options["filters"])
# @pytest.mark.parametrize("group_by_category", options["group_by_category"])
@pytest.mark.parametrize("summary", options["summary"])
def test_end_to_end_for_members(
    session_handler: PythonHandler,
    inherited_members: list[str] | bool | None,
    members: list[str] | bool | None,
    members_order: str,
    filters: list[str] | None,
    # group_by_category: bool,
    summary: bool | dict[str, bool] | None,
) -> None:
    """Test rendering of a given theme's templates.

    Parameters:
        identifier: Parametrized identifier.
        session_handler: Python handler (fixture).
    """
    final_options = {
        "inherited_members": inherited_members,
        "members": members,
        "members_order": members_order,
        "filters": filters,
        "summary": summary,
    }
    html = _render_options(final_options) + _render(session_handler, final_options)
    snapshot_key = tuple(sorted(final_options.items()))
    assert outsource(html, suffix=".html") == snapshots_members[snapshot_key]
